"""Profiler analysis tools for LeJEPA.

Classifies PyTorch profiler operations into 4 core architectural categories:
1. CPU Compute: CPU math, GEMMs, attention, activations, layer norms, convolutions
2. GPU Compute: CUDA/device compute kernels
3. CPU-Mem I/O: CPU memory allocations, copies, clone, contiguous, slicing, reshaping
4. CPU-GPU I/O: Host-to-device and device-to-host transfers (aten::to, memcpy)
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

MEM_IO_EXACT = {
    "copy_",
    "clone",
    "contiguous",
    "empty",
    "empty_like",
    "empty_strided",
    "cat",
    "stack",
    "pad",
    "replication_pad3d",
    "flip",
    "select",
    "slice",
    "narrow",
    "view",
    "_unsafe_view",
    "reshape",
    "transpose",
    "t",
    "permute",
    "expand",
    "unsqueeze",
    "flatten",
    "as_strided",
    "resize_",
    "fill_",
    "resolve_conj",
    "split",
}

CPU_GPU_IO_EXACT = {
    "to",
    "_to_copy",
    "pin_memory",
    "is_pinned",
    "item",
    "_local_scalar_dense",
}


def _clean_op_name(name: str) -> str:
    """Strip aten:: namespace and lower-case."""
    return name.replace("aten::", "").lower().strip()


def categorize_op(name: str, has_cuda: bool = False, is_cuda_event: bool = False) -> str:
    """Categorize an operator name into one of 4 buckets."""
    op_clean = _clean_op_name(name)
    name_lower = name.lower()

    # CPU-GPU I/O
    if (
        op_clean in CPU_GPU_IO_EXACT
        or "memcpy" in name_lower
        or "htod" in name_lower
        or "dtoh" in name_lower
        or "cudamemcpy" in name_lower
    ):
        return "CPU-GPU I/O"

    # GPU Compute (CUDA kernels / events)
    if is_cuda_event or "cuda" in name_lower and not ("memcpy" in name_lower or "memset" in name_lower):
        return "GPU Compute"

    # CPU-Mem I/O
    if op_clean in MEM_IO_EXACT or "memset" in name_lower:
        return "CPU-Mem I/O"

    # Default to CPU Compute for math/ops
    return "CPU Compute"


def _parse_time_us(t_str: str) -> float:
    t_str = t_str.strip()
    if t_str.endswith("ms"):
        return float(t_str[:-2]) * 1000.0
    elif t_str.endswith("us"):
        return float(t_str[:-2])
    elif t_str.endswith("s"):
        return float(t_str[:-1]) * 1_000_000.0
    try:
        return float(t_str)
    except ValueError:
        return 0.0


def _format_time(us: float) -> str:
    if us >= 1_000_000.0:
        return f"{us / 1_000_000.0:.3f} s"
    elif us >= 1_000.0:
        return f"{us / 1_000.0:.2f} ms"
    return f"{us:.1f} us"


def analyze_key_averages(key_averages: Any) -> Dict[str, Any]:
    """Analyze torch.profiler.key_averages() object."""
    cat_times: Dict[str, float] = {
        "CPU Compute": 0.0,
        "GPU Compute": 0.0,
        "CPU-Mem I/O": 0.0,
        "CPU-GPU I/O": 0.0,
    }
    top_ops: Dict[str, Dict[str, float]] = {k: {} for k in cat_times}

    for k in key_averages:
        name = getattr(k, "key", str(k))
        self_cpu_us = float(getattr(k, "self_cpu_time_total", 0.0) or 0.0)
        cuda_us = float(
            getattr(k, "self_device_time_total", 0.0)
            or getattr(k, "cuda_time_total", 0.0)
            or 0.0
        )

        # Classify CPU time
        if self_cpu_us > 0:
            cat = categorize_op(name, is_cuda_event=False)
            cat_times[cat] += self_cpu_us
            top_ops[cat][name] = top_ops[cat].get(name, 0.0) + self_cpu_us

        # Classify GPU time
        if cuda_us > 0:
            if "memcpy" in name.lower() or "to" in name.lower():
                cat = "CPU-GPU I/O"
            else:
                cat = "GPU Compute"
            cat_times[cat] += cuda_us
            top_ops[cat][name] = top_ops[cat].get(name, 0.0) + cuda_us

    return _build_result(cat_times, top_ops)


def analyze_profile_out(text: str) -> Dict[str, Any]:
    """Analyze a profile.out table generated by torch.profiler."""
    cat_times: Dict[str, float] = {
        "CPU Compute": 0.0,
        "GPU Compute": 0.0,
        "CPU-Mem I/O": 0.0,
        "CPU-GPU I/O": 0.0,
    }
    top_ops: Dict[str, Dict[str, float]] = {k: {} for k in cat_times}

    lines = text.splitlines()
    for line in lines:
        if line.startswith("-") or "Self CPU time total:" in line or "Name" in line:
            continue
        parts = line.split()
        if len(parts) < 4:
            continue
        name = parts[0]
        # parts[2] is Self CPU in PyTorch profiler table
        self_cpu_str = parts[2]
        t_us = _parse_time_us(self_cpu_str)
        if t_us <= 0:
            continue

        cat = categorize_op(name)
        cat_times[cat] += t_us
        top_ops[cat][name] = top_ops[cat].get(name, 0.0) + t_us

    return _build_result(cat_times, top_ops)


def analyze_chrome_trace(json_data: Union[dict, list, str, Path]) -> Dict[str, Any]:
    """Analyze a profile.json Chrome trace event file."""
    if isinstance(json_data, (str, Path)):
        with open(json_data, "r") as f:
            data = json.load(f)
    else:
        data = json_data

    events = data.get("traceEvents", []) if isinstance(data, dict) else data

    cat_times: Dict[str, float] = {
        "CPU Compute": 0.0,
        "GPU Compute": 0.0,
        "CPU-Mem I/O": 0.0,
        "CPU-GPU I/O": 0.0,
    }
    top_ops: Dict[str, Dict[str, float]] = {k: {} for k in cat_times}

    for ev in events:
        if not isinstance(ev, dict) or "dur" not in ev:
            continue
        name = ev.get("name", "")
        dur_us = float(ev.get("dur", 0.0))
        cat_tag = ev.get("cat", "")

        is_cuda = cat_tag in ("cuda_kernel", "gpu_user_annotation") or "cuda" in cat_tag.lower()
        cat = categorize_op(name, is_cuda_event=is_cuda)
        cat_times[cat] += dur_us
        top_ops[cat][name] = top_ops[cat].get(name, 0.0) + dur_us

    return _build_result(cat_times, top_ops)


def _build_result(
    cat_times: Dict[str, float], top_ops: Dict[str, Dict[str, float]]
) -> Dict[str, Any]:
    total_us = sum(cat_times.values()) or 1.0
    percentages = {cat: (t / total_us) * 100.0 for cat, t in cat_times.items()}

    sorted_cats = sorted(cat_times.items(), key=lambda x: x[1], reverse=True)
    primary_category = sorted_cats[0][0] if sorted_cats else "CPU Compute"

    return {
        "total_time_us": total_us,
        "times_us": cat_times,
        "percentages": percentages,
        "top_ops": top_ops,
        "primary_bottleneck": primary_category,
    }


def format_bottleneck_report(analysis: Dict[str, Any]) -> str:
    """Generate a clean ASCII table report from analysis results."""
    total_us = analysis["total_time_us"]
    times = analysis["times_us"]
    pcts = analysis["percentages"]
    top_ops = analysis["top_ops"]
    primary = analysis["primary_bottleneck"]

    lines = [
        "=" * 82,
        "                          BOTTLENECK ANALYSIS SUMMARY",
        "=" * 82,
        f"{'Category':<15} | {'Duration':<10} | {'% Total':<8} | Key Contributing Operations",
        "-" * 82,
    ]

    for cat in ["CPU Compute", "GPU Compute", "CPU-Mem I/O", "CPU-GPU I/O"]:
        t_us = times.get(cat, 0.0)
        pct = pcts.get(cat, 0.0)
        ops = top_ops.get(cat, {})
        sorted_ops = sorted(ops.items(), key=lambda x: x[1], reverse=True)[:2]
        if sorted_ops:
            ops_str = ", ".join(f"{op} ({_format_time(t)})" for op, t in sorted_ops)
        else:
            ops_str = "(None)"
        lines.append(f"{cat:<15} | {_format_time(t_us):<10} | {pct:>6.1f}% | {ops_str}")

    lines.append("-" * 82)
    lines.append(f"Primary Bottleneck: {primary} ({pcts.get(primary, 0.0):.1f}% of profiled time)")

    # Actionable diagnostic tip
    if primary == "CPU Compute":
        if times.get("GPU Compute", 0.0) == 0.0:
            lines.append("Recommendation: Run on GPU (`model.to('cuda')`). Computation is CPU-bound.")
        else:
            lines.append("Recommendation: CPU overhead is stalling GPU. Check multi-processing/pin_memory.")
    elif primary == "GPU Compute":
        lines.append("Recommendation: Fully GPU compute-bound. Try torch.compile, fp16/bf16, or flash attention.")
    elif primary == "CPU-GPU I/O":
        lines.append("Recommendation: Host-to-Device transfer bottleneck. Use non_blocking=True and pin_memory=True.")
    elif primary == "CPU-Mem I/O":
        lines.append("Recommendation: Memory copying/reshaping overhead. Minimize clones, views, or inplace ops.")

    lines.append("=" * 82)
    lines.append("")
    return "\n".join(lines)


def analyze_and_format(target: Union[str, Path, Any]) -> str:
    """Analyze a profiler object, .out file, or .json file and return formatted report."""
    if hasattr(target, "key_averages"):
        analysis = analyze_key_averages(target.key_averages())
    elif isinstance(target, (str, Path)):
        p = Path(target)
        if p.suffix == ".json":
            analysis = analyze_chrome_trace(p)
        else:
            analysis = analyze_profile_out(p.read_text())
    elif isinstance(target, str) and "Self CPU" in target:
        analysis = analyze_profile_out(target)
    else:
        raise ValueError(f"Unsupported target for profile analysis: {type(target)}")

    return format_bottleneck_report(analysis)


def main() -> None:
    """CLI entrypoint: python -m llm.profiler [file_path]"""
    args = sys.argv[1:]
    path = Path(args[0]) if args else Path("outdir/e00/main/basic/profile.out")
    if not path.exists():
        print(f"Error: file '{path}' does not exist.")
        sys.exit(1)
    print(analyze_and_format(path))


if __name__ == "__main__":
    main()
